<?php

namespace ContainerP7Gf0NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDBServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DB\DBService' shared autowired service.
     *
     * @return \App\Service\DB\DBService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/DB/DBService.php';

        return $container->privates['App\\Service\\DB\\DBService'] = new \App\Service\DB\DBService(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
