<?php

namespace ContainerP7Gf0NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Functional\SystemController' shared autowired service.
     *
     * @return \App\Controller\Functional\SystemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Functional/SystemController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SystemService.php';

        $container->services['App\\Controller\\Functional\\SystemController'] = $instance = new \App\Controller\Functional\SystemController(new \App\Service\SystemService(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)))));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Functional\\SystemController', $container));

        return $instance;
    }
}
