<?php

namespace ContainerP7Gf0NX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScriptsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Resource\ScriptsController' shared autowired service.
     *
     * @return \App\Controller\Resource\ScriptsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Resource/ScriptsController.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/ScriptFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/TagFactory.php';

        $container->services['App\\Controller\\Resource\\ScriptsController'] = $instance = new \App\Controller\Resource\ScriptsController(($container->privates['App\\Service\\ScriptService'] ?? $container->load('getScriptServiceService')), new \App\Factory\ScriptFactory(), new \App\Factory\TagFactory());

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Resource\\ScriptsController', $container));

        return $instance;
    }
}
