doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: false
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      string_functions:
        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
        field: DoctrineExtensions\Query\Mysql\Field
      numeric_functions:
        IFNULL: DoctrineExtensions\Query\Mysql\IfNull
      datetime_functions:
        date: DoctrineExtensions\Query\Mysql\Date