<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6qY4Lh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6qY4Lh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6qY4Lh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6qY4Lh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6qY4Lh\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6qY4Lh',
    'container.build_id' => 'f551ae43',
    'container.build_time' => 1692167943,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6qY4Lh');
