<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAaS2UR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAaS2UR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAaS2UR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAaS2UR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLAaS2UR\App_KernelDevDebugContainer([
    'container.build_hash' => 'LAaS2UR',
    'container.build_id' => '5be4117e',
    'container.build_time' => 1690649552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAaS2UR');
