<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP7Gf0NX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP7Gf0NX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP7Gf0NX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP7Gf0NX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP7Gf0NX\App_KernelDevDebugContainer([
    'container.build_hash' => 'P7Gf0NX',
    'container.build_id' => '768f38b1',
    'container.build_time' => 1692153433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP7Gf0NX');
