<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseBackupControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Resource\DatabaseBackupController' shared autowired service.
     *
     * @return \App\Controller\Resource\DatabaseBackupController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Resource/DatabaseBackupController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseBackupService.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/DatabaseBackupFactory.php';

        $a = new \App\Factory\DatabaseBackupFactory();

        $container->services['App\\Controller\\Resource\\DatabaseBackupController'] = $instance = new \App\Controller\Resource\DatabaseBackupController(new \App\Service\DatabaseBackupService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), $a, ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->privates['App\\Service\\DB\\DBService'] ?? $container->load('getDBServiceService'))), $a);

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Resource\\DatabaseBackupController', $container));

        return $instance;
    }
}
