<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Functional\FileController' shared autowired service.
     *
     * @return \App\Controller\Functional\FileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Functional/FileController.php';

        $container->services['App\\Controller\\Functional\\FileController'] = $instance = new \App\Controller\Functional\FileController(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Functional\\FileController', $container));

        return $instance;
    }
}
