<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Functional\GeneratorController' shared autowired service.
     *
     * @return \App\Controller\Functional\GeneratorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Functional/GeneratorController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/GeneratorService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GeneratePostmanTestService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateDtoCodeService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateFactoryCodeService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateControllerCodeService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateServiceCodeService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateSlateService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateApiTsInterfaceService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Generator/GenerateApiTsServiceCodeService.php';

        $a = ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));

        $container->services['App\\Controller\\Functional\\GeneratorController'] = $instance = new \App\Controller\Functional\GeneratorController(new \App\Service\GeneratorService(new \App\Service\Generator\GeneratePostmanTestService(), new \App\Service\Generator\GenerateDtoCodeService(), new \App\Service\Generator\GenerateFactoryCodeService(), new \App\Service\Generator\GenerateControllerCodeService(), new \App\Service\Generator\GenerateServiceCodeService(), new \App\Service\Generator\GenerateSlateService($a), new \App\Service\Generator\GenerateApiTsInterfaceService([]), new \App\Service\Generator\GenerateApiTsServiceCodeService(), ($container->privates['App\\Service\\RiskidService'] ?? $container->load('getRiskidServiceService')), $a));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Functional\\GeneratorController', $container));

        return $instance;
    }
}
