<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewmanTasksControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Resource\NewmanTasksController' shared autowired service.
     *
     * @return \App\Controller\Resource\NewmanTasksController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Resource/NewmanTasksController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/NewmanTaskService.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/NewmanTaskFactory.php';

        $container->services['App\\Controller\\Resource\\NewmanTasksController'] = $instance = new \App\Controller\Resource\NewmanTasksController(new \App\Service\NewmanTaskService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['custom_thing.cache'] ?? $container->load('getCustomThing_CacheService'))), new \App\Factory\NewmanTaskFactory());

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Resource\\NewmanTasksController', $container));

        return $instance;
    }
}
