<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationLogControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Resource\OperationLogController' shared autowired service.
     *
     * @return \App\Controller\Resource\OperationLogController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Resource/OperationLogController.php';

        $container->services['App\\Controller\\Resource\\OperationLogController'] = $instance = new \App\Controller\Resource\OperationLogController(($container->privates['App\\Service\\OperationLogService'] ?? $container->getOperationLogServiceService()));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Resource\\OperationLogController', $container));

        return $instance;
    }
}
