<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRiskidServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RiskidService' shared autowired service.
     *
     * @return \App\Service\RiskidService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RiskidService.php';

        return $container->privates['App\\Service\\RiskidService'] = new \App\Service\RiskidService(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->privates['App\\Service\\DB\\DBService'] ?? $container->load('getDBServiceService')));
    }
}
