<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRiskIdControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Functional\RiskIdController' shared autowired service.
     *
     * @return \App\Controller\Functional\RiskIdController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Functional/RiskIdController.php';

        $container->services['App\\Controller\\Functional\\RiskIdController'] = $instance = new \App\Controller\Functional\RiskIdController(($container->privates['App\\Service\\RiskidService'] ?? $container->load('getRiskidServiceService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Functional\\RiskIdController', $container));

        return $instance;
    }
}
