<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScriptServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ScriptService' shared autowired service.
     *
     * @return \App\Service\ScriptService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ScriptService.php';

        return $container->privates['App\\Service\\ScriptService'] = new \App\Service\ScriptService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
