<?php

namespace ContainerN6qY4Lh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Resource\TagController' shared autowired service.
     *
     * @return \App\Controller\Resource\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Resource/TagController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TagService.php';

        $container->services['App\\Controller\\Resource\\TagController'] = $instance = new \App\Controller\Resource\TagController(new \App\Service\TagService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Resource\\TagController', $container));

        return $instance;
    }
}
