controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

functional_controllers:
  resource: ../../src/Controller/Functional/
  type: annotation
  prefix: '/functional'

resource_controllers:
    resource: ../../src/Controller/Resource/
    type: annotation
    prefix: '/resource'