controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

file_controllers:
  resource: ../../src/Controller/Functional/
  type: annotation
  prefix: '/functional'